### ISSUE TITLE
Cannot view dialogue from the Map Vendor

### ISSUE THREAD

**Issue by anneomcl** [punto-/mystery2#1]
The player's speech and dialogue options are all functioning as expected. However, none of the Map Vendor's replies are visible, though I've found that the correct text is being set after stepping through the code. Still figuring out how this system works but @punto- if you know a fix it'd be appreciated.

**Comment by punto-** [comment]
I can see the map vendor's dialog on my version.. Does it happen with all
the lines? The position of the dialog box is determined by the position of
the node "dialog_pos", which is a child of the map_vendor node in the main
scene, which is kind of in the middle of the screen. The speech scene is a
big label with centered text, so the actual text will show up to the upper
left of that position (does that make sense?). Did you change anything in
the map vendor or the speech scene? it's probably showing up outside of the
screen..

**Comment by anneomcl** [comment]
I made a branch called "Anne" with some of my changes. The text is not being rendered anywhere, but the correct dialogue IS being piped through. It's just not displaying. In the current version of the branch it's now not working for the player OR the vendor. Still trying to figure out what I changed that would cause that.

I'll keep digging since I'm sure it's a simple issue, but just wanted to see if there was a quick/known fix or variable.

**Comment by anneomcl** [comment]
Aha! Ok, so it was an issue with the vendor's dialogue position being set to somewhere far off camera. I'm not sure what I had changed to make the player's not work. Oh well, should be fine now.

**Comment by punto-** [comment]
Great :) Yeah.. the position is determined by a Node called "dialog_pos" child of the item that's speaking, or if not found its just the position of the item itself. The actual text will also have an offset since it's not exactly at 0,0 in the scene.. but we'll probably use speech scenes with global positions, so it shouldn't be an issue..                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: AnneSent: Friday, December 9, 2016 5:06 AMTo: punto-/mystery2Reply To: punto-/mystery2Cc: punto-; MentionSubject: Re: [punto-/mystery2] Cannot view dialogue from the Map Vendor (#1)Aha! Ok, so it was an issue with the vendor's dialogue position being set to somewhere far off camera. I'm not sure what I had changed to make the player's not work. Oh well, should be fine now.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/punto-/mystery2","title":"punto-/mystery2","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/punto-/mystery2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@anneomcl in #1: Aha! Ok, so it was an issue with the vendor's dialogue position being set to somewhere far off camera. I'm not sure what I had changed to make the player's not work. Oh well, should be fine now."}],"action":{"name":"View Issue","url":"https://github.com/punto-/mystery2/issues/1#issuecomment-265956720"}}}
